### ISSUE TITLE
Submission Feedback/Status

### ISSUE THREAD

**Issue by delsonting** [unlessdotcom/gtm-unless-installer#1]
This Tag Manager template submission has been approved and should be available in the Template Gallery within the next day. 

One recommendation to encode the data.unlessAccountId variable on line 65 using [encodeUriComponent](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) to make sure the user provided value is safe for urls.

**Comment by unlessdotcom** [comment]
👍 Thanks! We'll update this in the next version.
